# Generated by Django 2.2.3 on 2019-09-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logcommandresult',
            table='log_command_result',
        ),
    ]
