# Generated by Django 2.2.3 on 2019-09-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190924_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommandresult',
            name='node_id',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
