# Generated by Django 2.2.3 on 2019-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_logcommandresult_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcommandresult',
            name='login_time',
            field=models.DateTimeField(),
        ),
    ]
