# Generated by Django 2.2.3 on 2019-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190925_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommandresult',
            name='terminal_id',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
